//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalArena.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carousel
    {
        public int CarouselId { get; set; }
        public string Image { get; set; }
        public string Page { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedAt { get; set; }
    }
}
