//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalArena.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coupon
    {
        public int CouponId { get; set; }
        public string CouponCode { get; set; }
        public int DiscountPercentage { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public int MaxUsage { get; set; }
        public int UsageCount { get; set; }
        public bool UserSpecific { get; set; }
        public Nullable<int> UserId { get; set; }
        public int CreatedBy { get; set; }
    
        public virtual User User { get; set; }
    }
}
