//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalArena.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiftCard
    {
        public int GiftCardId { get; set; }
        public string GiftCode { get; set; }
        public decimal Amount { get; set; }
        public bool IsAvailable { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public Nullable<System.DateTime> UsedAt { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
