//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalArena.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class LandingPage
    {
        public int LandingPageId { get; set; }
        public int ProductId { get; set; }
        public string Headline { get; set; }
        public string SubHeadline { get; set; }
        public string HeroImage { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
