//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalArena.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderItem = new HashSet<OrderItem>();
        }
    
        public int OrderId { get; set; }
        public decimal Amount { get; set; }
        public string BillingAddress { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string Status { get; set; }
        public string PaymentStatus { get; set; }
        public Nullable<int> TransactionId { get; set; }
        public int UserId { get; set; }

        public virtual ICollection<OrderItem> OrderItems { get; set; }
        public virtual Transaction Transaction { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItem> OrderItem { get; set; }
    }
}
