//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalArena.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public int PermissionId { get; set; }
        public bool IsValid { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> LastDownloadedAt { get; set; }
        public int UserId { get; set; }
        public int ProductId { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
